[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[cmake]
symbol = "cmake "
