#!/bin/bash

items="poweroff
reboot
suspend
logout"

sel=$(printf '%s' "$items" | dmenu)

case $sel in
    poweroff)
        doas /sbin/poweroff
        ;;
    reboot)
        doas /sbin/reboot
        ;;
    suspend)
        loginctl suspend
        ;;
    logout)
        loginctl kill-user $USER
        ;;
esac
